name: Deploy to Web3

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    name: Deploy to Fleek
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: |
          cd client
          npm ci
          
      - name: Create env file
        run: |
          cd client
          echo "VITE_WEB3_MODE=true" > .env.production
          echo "CONTRACT_ADDRESS=${{ secrets.CONTRACT_ADDRESS }}" >> .env.production
          echo "VITE_API_URL=https://your-api-endpoint.vercel.app/api" >> .env.production
          
      - name: Build for Web3
        run: |
          cd client
          npm run build:web3
          
      - name: Deploy to Fleek
        uses: fleekhq/action-deploy@v1
        with:
          apiKey: ${{ secrets.FLEEK_API_KEY }}
          workDir: client/dist
          site: ${{ secrets.FLEEK_SITE_ID }} 